# Generated by Django 4.2.9 on 2024-04-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ODI_APP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rbi_odi',
        ),
    ]
